language: php
php: 7.2.2
before_script:
  - composer install
  - docker run --rm -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose .
  - docker run --rm -v $PWD:/app phpqa/security-checker security:check
  - php ./vendor/phpunit/phpunit/phpunit
notifications:
  email:
    on_success: never
    on_failure: always